export const itemTags = [
  "Activity Points",
  "Ascension Material",
  "Convene Exchange Token",
  "Convene Token",
  "Consumable",
  "Cooking Ingredient",
  "Crafting Material",
  "Dish",
  "Echo Development Material",
  "EXP",
  "Herb",
  "Material",
  "Medicine",
  "Premium Currency",
  "Processed Item",
  "Random Echo Item",
  "Resonator Ascension Material",
  "Resonator EXP Material",
  "Skill Upgrade Material",
  "Special Token",
  "Supply Pack",
  "Synthesis Recipe: Constructing",
  "Synthesis Recipe: Potion Making",
  "Universal Currency",
  "Utility",
  "Weapon & Skill Material",
  "Weapon EXP Material",
  "Weapon and Skill Material",
];
