export const itemTags = [
  "EXP",
  "Resonator EXP Material",
  "Weapon EXP Material",
  "Weapon and Skill Material",
  "Material",
  "Ascension Material",
  "Universal Currency",
  "Premium Currency",
  "Convene Token",
  "Convene Exchange Token",
  "Consumable",
  "Resonator Ascension Material",
  "Weapon & Skill Material",
  "Skill Upgrade Material",
  "Medicine",
  "Herb",
  "Cooking Ingredient",
  "Crafting Material",
  "Special Token",
  "Echo Development Material",
  "Quest Item",
  "Remnant Shard",
  "Dish",
  "Processed Item",
  "Synthesis Result: Medicine",
  "Synthesis Result: Gameplay Item",
  "Utility",
  "Activity Points",
  "Random Echo Item",
  "Supply Pack",
  "Synthesis Recipe: Constructing",
  "Synthesis Recipe: Potion Making",
];
