import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { ThemeProvider } from "@/components/ui/theme-provider";
import { Footer } from "@/components/ui/footer";
import "./globals.css";
import { Header } from "@/components/ui/header";
import { Sidebar } from "@/components/ui/sidebar";
import { Toaster } from "@/components/ui/sonner";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "WuWa Convene Tracker",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <div className="flex min-h-screen w-full flex-col bg-accent dark:bg-background">
            <Header />
            <div className="h-[80%] mb-3">
              <div className="flex h-full flex-col desktop:flex-row">
                <Sidebar />
                <div className="w-full">{children}</div>
              </div>
            </div>
            <Footer />
          </div>
        </ThemeProvider>
        <Toaster richColors />
      </body>
    </html>
  );
}
